#pragma once

#ifndef LZ_GENERATE_HPP
#define LZ_GENERATE_HPP

#include <Lz/detail/basic_iterable.hpp>
#include <Lz/detail/iterators/generate.hpp>

namespace lz {

LZ_MODULE_EXPORT_SCOPE_BEGIN

template<class GeneratorFunc>
class generate_iterable final : public detail::basic_iterable<detail::generate_iterator<GeneratorFunc>, default_sentinel> {
public:
    using iterator = detail::generate_iterator<GeneratorFunc>;
    using const_iterator = iterator;
    using value_type = typename iterator::value_type;

    LZ_CONSTEXPR_CXX_14
    generate_iterable(GeneratorFunc func, const std::size_t amount, const bool is_inf_loop) :
        detail::basic_iterable<iterator, default_sentinel>(iterator(amount, std::move(func), is_inf_loop)) {
    }

    constexpr generate_iterable() = default;
};

/**
 * @addtogroup ItFns
 * @{
 */

/**
 * This object can be used to generate `amount` of values, generated by the `generator_func` function.
 * Example:
 * ```cpp
 * int a = 0;
 * size_t amount = 4;
 * auto vector = lz::generate([](int& i) { auto tmp{a++}; return tmp; }, amount, 0).to_vector();
 * // vector yields: { 0, 1, 2, 3 }
 * @param generator_func The function to execute `amount` of times. The return value of the function is the type
 * that is generated.
 * ```
 * @param amount The amount of times to execute `generator_func`.
 * @param args Args to pass to the function @p generator_func
 * @return A generator iterator view object.
 */
template<class GeneratorFunc>
LZ_NODISCARD LZ_CONSTEXPR_CXX_14 generate_iterable<detail::decay_t<GeneratorFunc>>
generate(GeneratorFunc&& generator_func, const std::size_t amount = (std::numeric_limits<std::size_t>::max)()) {
    return { std::forward<GeneratorFunc>(generator_func), amount, amount == (std::numeric_limits<std::size_t>::max)() };
}

// End of group
/**
 * @}
 */

LZ_MODULE_EXPORT_SCOPE_END

} // namespace lz

#endif